Config.Groups = {
	{
		Name = "Dances",
		Icon = "music_note",
		Emotes = {
			["d"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_06_base_laz", Flag = 1 },
			["d2"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_06_base_v2_laz", Flag = 1 },
			["d3"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_15_lookaround_laz", Flag = 1 },
			["d4"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_li_06_base_laz", Flag = 1 },
			["dcenter"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", Name = "high_center", Flag = 1 },
			["dcenter2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center", Flag = 1 },
			["dcenterdown"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "high_center_down", Flag = 1 },
			["dcenterup"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "high_center_up", Flag = 1 },
			["dcenterup2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center_up", Flag = 1 },
			["dcenterup3"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "high_center_up", Flag = 1 },
			["dcradle"] = { Dict = "anim@mp_player_intuppercats_cradle", Name = "idle_a", Flag = 1 },
			["dcrotch"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_13_crotchgrab_laz", Flag = 1 },
			["dcrowd"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@", Name = "hi_dance_facedj_15_v2_female^6", Flag = 1 },
			["dcrowd2"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^1", Flag = 1 },
			["dcrowd3"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity", "hi_dance_facedj_09_v2_female^3", Flag = 1 },
			["dent"] = { Dict = "anim@amb@nightclub@dancers@solomun_entourage@", Name = "mi_dance_facedj_17_v1_female^1", Flag = 1 },
			["dentice"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_mi_13_enticing_laz", Flag = 1 },
			["dfish"] = { Dict = "anim@mp_player_intupperfind_the_fish", Name = "idle_a", Flag = 1 },
			["dfly"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_13_flyingv_laz", Flag = 1 },
			["dfly2"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_li_15_flyingv_laz", Flag = 1 },
			["dglow"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_06_mi_hi_base_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dglow2"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_06_mi_hi_base_v2_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dglow2"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_11_mi_hi_pointingcrowd_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dglowbelly"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_09_mi_hi_bellydancer_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dglowsex"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_13_mi_hi_sexualgriding_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dglowshake"] = { Dict = "anim@amb@nightclub@lazlow@hi_railing@", Name = "ambclub_12_mi_hi_bootyshake_laz", Flag = 1, Props = { { Model = `ba_prop_battle_glowstick_01`, Bone = 28422, Offset = { 0.0700, 0.1400, 0.0, -80.0, 20.0 }}, { Model = `ba_prop_battle_glowstick_01`, Bone = 60309, Offset = { 0.0700, 0.0900, 0.0, -120.0, -20.0 }} }},
			["dhorse"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_hi_11_handup_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsebuck"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_hi_15_buckingbronco_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsecrowd"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_hi_06_base_v2_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsepet"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_15_pethorse_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsepole"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_17_poledance_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorseslow"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_11_hu_shimmy_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsesmack"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "dancecrowd_li_13_smackthat_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsespank"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_mi_11_spankthat_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dhorsesuck"] = { Dict = "anim@amb@nightclub@lazlow@hi_dancefloor@", Name = "crowddance_hi_13_suckit_laz", Flag = 1, Props = { { Model = `ba_prop_battle_hobby_horse`, Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }} }},
			["dlap"] = { Dict = "mini@strip_club@private_dance@part1", Name = "priv_dance_p1", Flag = 1 },
			["dlap2"] = { Dict = "mini@strip_club@private_dance@part2", Name = "priv_dance_p2", Flag = 1 },
			["dlap3"] = { Dict = "mini@strip_club@private_dance@part3", Name = "priv_dance_p3", Flag = 1 },
			["dlap4"] = { Dict = "mp_am_stripper", Name = "lap_dance_girl", Flag = 1 },
			["dlap5"] = { Dict = "mini@strip_club@private_dance@idle", Name = "priv_dance_idle", Flag = 1 },
			["dlap6"] = { Dict = "mini@strip_club@lap_dance@ld_girl_a_song_a_p3", Name = "ld_girl_a_song_a_p3_f", Flag = 1 },
			["dmedcenter"] = { Dict = "anim@amb@casino@mini@dance@dance_solo@female@var_a@", Name = "med_center", Flag = 1 },
			["dmedcenterup"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "med_center_up", Flag = 1 },
			["dmix"] = { Dict = "anim@amb@nightclub@djs@dixon@", Name = "dixn_dance_cntr_open_dix", Flag = 1 },
			["dpodium"] = { Dict = "anim@amb@nightclub@dancers@podium_dancers@", Name = "hi_dance_facedj_17_v2_male^5", Flag = 1 },
			["dpoint"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_li_11_pointcrowd_laz", Flag = 1 },
			["dpole"] = { Dict = "mini@strip_club@pole_dance@pole_dance1", Name = "pd_dance_01", Flag = 1 },
			["dpole2"] = { Dict = "mini@strip_club@pole_dance@pole_dance2", Name = "pd_dance_02", Flag = 1 },
			["dpole3"] = { Dict = "mini@strip_club@pole_dance@pole_dance3", Name = "pd_dance_03", Flag = 1 },
			["dprivatedance"] = { Dict = "anim@amb@nightclub@peds@", Name = "mini_strip_club_lap_dance_ld_girl_a_song_a_p1", Flag = 1 },
			["dprivatedanceidle"] = { Dict = "anim@amb@nightclub@peds@", Name = "mini_strip_club_private_dance_idle_priv_dance_idle", Flag = 1 },
			["dpumpdance"] = { Dict = "anim@mp_player_intupperheart_pumping", Name = "idle_a", Flag = 1 },
			["drobot"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_15_crazyrobot_laz", Flag = 1 },
			["dsexygrind"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_li_15_sexygrind_laz", Flag = 1 },
			["dshy"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_a@", Name = "low_center", Flag = 1 },
			["dshy2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "low_center_down", Flag = 1 },
			["dsilly"] = { Dict = "special_ped@mountain_dancer@monologue_3@monologue_3a", "mnt_dnc_buttwag", Flag = 1 },
			["dsilly2"] = { Dict = "move_clown@p_m_zero_idles@", Name = "fidget_short_dance", Flag = 1 },
			["dsilly3"] = { Dict = "move_clown@p_m_two_idles@", Name = "fidget_short_dance", Flag = 1 },
			["dsilly4"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_11_buttwiggle_b_laz", Flag = 1 },
			["dsilly5"] = { Dict = "timetable@tracy@ig_5@idle_a", "idle_a", Flag = 1 },
			["dsilly6"] = { Dict = "timetable@tracy@ig_8@idle_b", "idle_d", Flag = 1 },
			["dsilly7"] = { Dict = "anim@amb@casino@mini@dance@dance_solo@female@var_b@", Name = "high_center", Flag = 1 },
			["dsilly8"] = { Dict = "anim@mp_player_intcelebrationfemale@the_woogie", "the_woogie", Flag = 1 },
			["dsilly9"] = { Dict = "rcmnigel1bnmt_1b", "dance_loop_tyler", Flag = 1 },
			["dslow"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@male@var_b@", Name = "low_center", Flag = 1 },
			["dslow2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "low_center", Flag = 1 },
			["dslow3"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_a@", Name = "low_center_down", Flag = 1 },
			["dslow4"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "low_center", Flag = 1 },
			["dsmackthat"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_17_smackthat_laz", Flag = 1 },
			["dspiderdance"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_17_spiderman_laz", Flag = 1 },
			["dteapotdance"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_mi_17_teapotthrust_laz", Flag = 1 },
			["dtunes"] = { Dict = "anim@mp_player_intupperbanging_tunes", Name = "idle_a", Flag = 1 },
			["dtunes2"] = { Dict = "anim@mp_player_intupperbanging_tunes_right", Name = "idle_a", Flag = 1 },
			["dturnaround"] = { Dict = "anim@amb@nightclub@lazlow@hi_podium@", Name = "danceidle_hi_11_turnaround_laz", Flag = 1 },
			["dtwerk"] = { Dict = "switch@trevor@mocks_lapdance", Name = "001443_01_trvs_28_idle_stripper", Flag = 1 },
			["dupper"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "high_center", Flag = 1 },
			["dupper2"] = { Dict = "anim@amb@nightclub@mini@dance@dance_solo@female@var_b@", Name = "high_center_up", Flag = 1 },
			["dvibe"] = { Dict = "anim@amb@nightclub@dancers@crowddance_facedj@", Name = "hi_dance_facedj_11_v2_male^2", Flag = 1 },
		},
	},
	{
		Name = "Greetings",
		Icon = "emoji_people",
		Emotes = {
			["greet"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_1", Flag = 48 },
			["greet2"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_2", Flag = 48 },
			["greet3"] = { Dict = "friends@frt@ig_1", Name = "trevor_arrival_3", Flag = 48 },
			["w"] = { Dict = "friends@frj@ig_1", Name = "wave_a", Flag = 0, BlendSpeed = 1.0 },
			["w3"] = { Dict = "friends@frj@ig_1", Name = "wave_b", Flag = 48, BlendSpeed = 1.0 },
			["w4"] = { Dict = "random@mugging5", Name = "001445_01_gangintimidation_1_female_idle_b", Flag = 49, BlendSpeed = 1.0 },
			["w5"] = { Dict = "friends@frj@ig_1", Name = "wave_b", Flag = 48, BlendSpeed = 1.0 },
			["w7"] = { Dict = "friends@frj@ig_1", Name = "wave_e", Flag = 48, BlendSpeed = 1.0 },
			["w8"] = { Dict = "friends@frj@ig_1", Name = "wave_e", Flag = 48, BlendSpeed = 1.0 },
			["w9"] = { Dict = "random@gang_intimidation@", Name = "001445_01_gangintimidation_1_female_wave_loop", Flag = 49, BlendSpeed = 1.0 },
			["wcrowd"] = { Dict = "anim@mp_player_intcelebrationfemale@wave", Name = "wave", Flag = 48, BlendSpeed = 1.0 },
			["wlow"] = { Dict = "anim@amb@waving@male", Name = "ground_wave", Flag = 0 },
			["wme"] = { Dict = "friends@frj@ig_1", Name = "wave_c", Flag = 48, BlendSpeed = 1.0 },
			["wno"] = { Dict = "friends@frj@ig_1", Name = "wave_d", Flag = 48, BlendSpeed = 1.0 },
			["wno2"] = { Dict = "friends@frj@ig_1", Name = "wave_d", Flag = 48, BlendSpeed = 1.0 },
			["wsassy"] = { Dict = "friends@fra@ig_1", Name = "over_here_idle_a", Flag = 48, BlendSpeed = 1.0 },
			["wshort"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", Flag = 48, BlendSpeed = 2.0 },
			["wshort2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", Flag = 48, BlendSpeed = 2.0 },
			["wslob"] = { Dict = "anim@mp_player_intcelebrationmale@wave", Name = "wave", Flag = 0 },
			["wup"] = { Dict = "anim@amb@waving@male", Name = "air_wave", Flag = 0 },
		},
	},
	{
		Name = "Sitting",
		Icon = "self_improvement",
		Emotes = {
			["s1"] = { Dict = "anim@amb@business@bgen@bgen_no_work@", Name = "sit_phone_phoneputdown_idle_nowork", Flag = 1 },
			["s2"] = { Dict = "rcm_barry3", Name = "barry_3_sit_loop", Flag = 1 },
			["s3"] = { Dict = "amb@world_human_picnic@male@idle_a", Name = "idle_a", Flag = 1 },
			["s4"] = { Dict = "amb@world_human_picnic@female@base", Name = "base", Flag = 1 },
			["s5"] = { Dict = "anim@heists@fleeca_bank@ig_7_jetski_owner", Name = "owner_idle", Flag = 1 },
			["s6"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "idle_a_jimmy", Flag = 1 },
			["s7"] = { Dict = "anim@amb@nightclub@lazlow@lo_alone@", Name = "lowalone_base_laz", Flag = 1 },
			["s8"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "mics3_15_base_jimmy", Flag = 1 },
			["s9"] = { Dict = "amb@world_human_stupor@male@idle_a", Name = "idle_a", Flag = 1 },
			["schair2"] = { Dict = "timetable@ron@ig_5_p3", Name = "ig_5_p3_base", Flag = 1 },
			["schair3"] = { Dict = "timetable@reunited@ig_10", Name = "base_amanda", Flag = 1 },
			["schair4"] = { Dict = "timetable@ron@ig_3_couch", Name = "base", Flag = 1 },
			["schair5"] = { Dict = "timetable@jimmy@mics3_ig_15@", Name = "mics3_15_base_tracy", Flag = 1 },
			["schair6"] = { Dict = "timetable@maid@couch@", Name = "base", Flag = 1 },
			["schairside"] = { Dict = "timetable@ron@ron_ig_2_alt1", Name = "ig_2_alt1_base", Flag = 1 },
			["sdrunk"] = { Dict = "timetable@amanda@drunk@base", Name = "base", Flag = 1 },
			["slean"] = { Dict = "timetable@tracy@ig_14@", Name = "ig_14_base_tracy", Flag = 1 },
			["ssad"] = { Dict = "anim@amb@business@bgen@bgen_no_work@", Name = "sit_phone_phoneputdown_sleeping-noworkfemale", Flag = 1 },
			["sscared"] = { Dict = "anim@heists@ornate_bank@hostages@hit", Name = "hit_loop_ped_b", Flag = 1 },
			["sscared2"] = { Dict = "anim@heists@ornate_bank@hostages@ped_c@", Name = "flinch_loop", Flag = 1 },
			["sscared3"] = { Dict = "anim@heists@ornate_bank@hostages@ped_e@", Name = "flinch_loop", Flag = 1 },
		},
	},
	{
		Name = "Gestures",
		Icon = "thumb_up",
		Emotes = {
			["bringit"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bring_it_on", Flag = 48 },
			["bye"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bye_hard", Flag = 48 },
			["bye2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_bye_soft", Flag = 48 },
			["chinbrush"] = { Dict = "anim@mp_player_intupperchin_brush", Name = "exit", Flag = 48 },
			["cmon"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atad_01_g3", Flag = 48 },
			["come"] = { Dict = "gestures@m@standing@casual", Name = "gesture_come_here_hard", Flag = 48 },
			["come2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_come_here_soft", Flag = 48 },
			["cutit"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atag_01_g2", Flag = 48 },
			["damn"] = { Dict = "gestures@m@standing@casual", Name = "gesture_damn", Flag = 48 },
			["displeased"] = { Dict = "gestures@m@standing@casual", Name = "gesture_displeased", Flag = 48 },
			["easy"] = { Dict = "gestures@m@standing@casual", Name = "gesture_easy_now", Flag = 48 },
			["handleft"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_left", Flag = 48 },
			["handright"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_right", Flag = 48 },
			["hello"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hello", Flag = 48 },
			["how"] = { Dict = "gestures@miss@dockssetup1", Name = "trevor_dh1_aeaa_01_g2", Flag = 48 },
			["iwill"] = { Dict = "gestures@m@standing@casual", Name = "gesture_i_will", Flag = 48 },
			["me"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me", Flag = 48 },
			["me2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_me_hard", Flag = 48 },
			["mine"] = { Dict = "gestures@m@standing@casual", Name = "getsure_its_mine", Flag = 48 },
			["no"] = { Dict = "gestures@m@standing@casual", Name = "gesture_no_way", Flag = 48 },
			["no2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_no_hard", Flag = 48 },
			["no3"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_no_soft", Flag = 48 },
			["nod"] = { Dict = "gestures@m@standing@casual", Name = "gesture_pleased", Flag = 48 },
			["nod2"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atae_01_g1", Flag = 48 },
			["now"] = { Dict = "gestures@m@standing@casual", Name = "gesture_hand_down", Flag = 48 },
			["point"] = { Dict = "gestures@m@standing@casual", Name = "gesture_point", Flag = 48 },
			["shrug"] = { Dict = "gestures@m@standing@casual", Name = "gesture_shrug_hard", Flag = 48 },
			["shrug2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_shrug_soft", Flag = 48 },
			["shrug3"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_afac_01_g1", Flag = 48 },
			["smh"] = { Dict = "gestures@m@standing@casual", Name = "gesture_head_no", Flag = 48 },
			["there"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_asab_01_g2", Flag = 48 },
			["there2"] = { Dict = "gestures@miss@dockssetup1", Name = "floyd_dh1_atab_01_g2", Flag = 48 },
			["upndown"] = { Dict = "gestures@miss@dockssetup1", Name = "trevor_dh1_aeaa_01_g1", Flag = 48 },
			["wesmart"] = { Dict = "gestures@miss@fra_0", Name = "lamar_fkn0_cjae_01_g4", Flag = 48 },
			["what"] = { Dict = "gestures@m@standing@casual", Name = "gesture_what_hard", Flag = 48 },
			["what2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_what_soft", Flag = 48 },
			["why"] = { Dict = "gestures@m@standing@casual", Name = "gesture_why", Flag = 48 },
			["why2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_why_left", Flag = 48 },
			["yep"] = { Dict = "gestures@miss@dockssetup1", Name = "trevor_dh1_ataf_01_g2", Flag = 48 },
			["yes"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_yes_hard", Flag = 48 },
			["yes2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_nod_yes_soft", Flag = 48 },
			["you"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_hard", Flag = 48 },
			["you2"] = { Dict = "gestures@m@standing@casual", Name = "gesture_you_soft", Flag = 48 },
		},
	},
	{
		Name = "Exercise",
		Icon = "fitness_center",
		Emotes = {
			["aerobics"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_a", Flag = 1 },
			["aerobics2"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_b", Flag = 1 },
			["aerobics3"] = { Dict = "timetable@tracy@ig_5@idle_a", Name = "idle_c", Flag = 1 },
			["aerobics4"] = { Dict = "timetable@tracy@ig_5@idle_b", Name = "idle_d", Flag = 1 },
			["flex"] = { Dict = "amb@world_human_muscle_flex@arms_at_side@idle_a", Name = "idle_a", Flag = 48 },
			["flex2"] = { Dict = "amb@world_human_muscle_flex@arms_in_front@base", Name = "base", Flag = 48 },
			["flex3"] = { Dict = "amb@world_human_muscle_flex@arms_in_front@idle_a", Name = "idle_b", Flag = 48 },
			["pullups"] = { Dict = "amb@prop_human_muscle_chin_ups@male@base", Name = "base", Flag = 1 },
			["yoga"] = { Dict = "amb@world_human_yoga@female@base", Name = "base_c", Flag = 1 },
			["yoga2"] = { Dict = "timetable@amanda@ig_4", Name = "ig_4_idle", Flag = 1 },
			["pushups"] = { Sequence = {
				{ Dict = "amb@world_human_push_ups@male@enter", Name = "enter", Flag = 0  },
				{ Dict = "amb@world_human_push_ups@male@idle_a", Name = "idle_d", Flag = 1  },
				{ Dict = "amb@world_human_push_ups@male@exit", Name = "exit", Flag = 0, Locked = true },
			}},
			["situps"] = { Sequence = {
				{ Dict = "amb@world_human_sit_ups@male@enter", Name = "enter", Flag = 0  },
				{ Dict = "amb@world_human_sit_ups@male@idle_a", Name = "idle_a", Flag = 1  },
				{ Dict = "amb@world_human_sit_ups@male@exit", Name = "exit", Flag = 0, Locked = true },
			}},
			["situps2"] = { Sequence = {
				{ Dict = "amb@world_human_sit_ups@male@enter", Name = "enter", Flag = 0  },
				{ Dict = "amb@world_human_sit_ups@male@idle_a", Name = "idle_c", Flag = 1  },
				{ Dict = "amb@world_human_sit_ups@male@exit", Name = "exit", Flag = 0, Locked = true },
			}},
		},
	},
	{
		Name = "Weird",
		Icon = "mood",
		Emotes = {
			["ballscratch"] = { Dict = "amb@code_human_in_car_mp_actions@grab_crotch@std@ds@base", Name = "idle_a", Flag = 49 },
			["bark"] = { Dict = "random@peyote@dog", Name = "wakeup", Flag = 0 },
			["bark2"] = { Dict = "random@peyote@dog", Name = "wakeup_loop", Flag = 1 },
			["bend"] = { Dict = "random@peyote@deer", Name = "wakeup_loop", Flag = 1 },
			["boobs"] = { Dict = "mini@strip_club@backroom@", Name = "stripper_b_backroom_idle_b", Flag = 48 },
			["chicken"] = { Dict = "anim@mp_player_intincarchicken_tauntstd@ps@", Name = "idle_a", Flag = 1 },
			["chicken2"] = { Dict = "anim@mp_player_intincarchicken_tauntstd@rds@", Name = "idle_a", Flag = 1 },
			["chicken3"] = { Dict = "random@peyote@chicken", Name = "wakeup", Flag = 0 },
			["crotch"] = { Dict = "mp_player_int_uppergrab_crotch", Name = "mp_player_int_grab_crotch", Flag = 49 },
		},
	},
	{
		Name = "Props",
		Icon = "iron",
		Emotes = {
			["carrybox"] = { Dict = "anim@heists@box_carry@", Name = "idle", Flag = 49, Props = {
				{ Model = "prop_cs_cardbox_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
			}, DisableCombat = true },
			
			["map2"] = { Dict = "amb@world_human_tourist_map@female@idle_a", Name = "idle_a", "Map", Flag = 49, Props = {
				{ Model = "prop_tourist_map_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }},
			}},
			["tablet"] = { Dict = "amb@code_human_in_bus_passenger_idles@female@tablet@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_cs_tablet", Bone = 60309, Offset = { 0.03, 0.002, 0.0, 10.0, -20.0, 0.0 }},
			}},
			["umbrella"] = { Dict = "amb@world_human_drinking@coffee@male@base", Name = "base", Flag = 49, Props = {
				{ Model = "p_amb_brolly_01", Bone = 57005, Offset = { 0.15, 0.005, 0.0, 87.0, -20.0, 180.0 } },
			}},
			["notepad"] = { Dict = "missheistdockssetup1clipboard@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_notepad_01", Bone = 18905, Offset = { 0.1, 0.02, 0.05, 10.0, 0.0, 0.0 } },
				{ Model = "prop_pencil_01", Bone = 58866, Offset = {  0.11, -0.02, 0.001, -120.0, 0.0, 0.0  } },
			}},
			["rose"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
				{ Model = "prop_single_rose", Bone = 18905, Offset = { 0.13, 0.15, 0.0, -100.0, 0.0, -20.0 } },
			}},
			["suitcase"] = { Dict = "amb@code_human_wander_purse@female@base", Name = "static", Flag = 49, Props = {
				{ Model = "prop_security_case_01", Bone = 57005, Offset = { 0.12, 0.0, 0.0, 90.0, 0.0, -100.0 } },
			}},
			["medbag"] = { Dict = "amb@code_human_wander_purse@female@base", Name = "static", Flag = 49, Props = {
				{ Model = "xm_prop_x17_bag_med_01a", Bone = 57005, Offset = { 0.41, -0.05, -0.03, 90.0, 0.0, -100.0 } },
			}},
			["mugshot"] = { Dict = "mp_character_creation@customise@male_a", Name = "loop", Flag = 49, Props = {
				{ Model = "prop_police_id_board", Bone = 58868, Offset = { 0.12, 0.24, 0.0, 5.0, 0.0, 70.0 } },
			}},
			["coffee"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
				{ Model = "p_amb_coffeecup_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["whiskey"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
				{ Model = "prop_drink_whisky", Bone = 28422, Offset = { 0.01, -0.01, -0.06, 0.0, 0.0, 0.0 } },
			}},
			["beer"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
				{ Model = "prop_amb_beer_bottle", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["cup"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
				{ Model = "prop_plastic_cup_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["donut"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
				{ Model = "prop_amb_donut", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
			}},
			["burger"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
				{ Model = "prop_cs_burger_01", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
			}},
			["busted"] = {
				Sequence = {
					{
						Unarmed = { Dict = "busted", Name = "idle_2_hands_up", Flag = 0 },
						Armed = {
							["1h"] = { Dict = "busted", Name = "idle_2_hands_up_2h", Flag = 0, Disarm = 3000 },
							["2h"] = { Dict = "busted", Name = "idle_2_hands_up_2h", Flag = 0, Disarm = 3000 },
						},
					},
					{ Dict = "busted", Name = "idle_a", Flag = 1 },
					{ Dict = "busted", Name = "hands_up_2_idle", Flag = 0 },
				},
			},
			["sandwich"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
				{ Model = "prop_sandwich_01", Bone = 18905, Offset = { 0.13, 0.05, 0.02, -50.0, 16.0, 60.0 } },
			}},
			["soda"] = { Dict = "amb@world_human_drinking@coffee@male@idle_a", Name = "idle_c", Flag = 49, Props = {
				{ Model = "prop_ecola_can", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 130.0 } },
			}},
			["egobar"] = { Dict = "mp_player_inteat@burger", Name = "mp_player_int_eat_burger", Flag = 49, Props = {
				{ Model = "prop_choc_ego", Bone = 60309, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["wine"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
				{ Model = "prop_drink_redwine", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
			}},
			["flute"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
				{ Model = "prop_champ_flute", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
			}},
			["champagne"] = { Dict = "anim@heists@humane_labs@finale@keycards", Name = "ped_a_enter_loop", Flag = 49, Props = {
				{ Model = "prop_drink_champ", Bone = 18905, Offset = { 0.10, -0.03, 0.03, -100.0, 0.0, -10.0 } },
			}},
			["guitar"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
				{ Model = "prop_acc_guitar_01", Bone = 24818, Offset = { -0.1, 0.31, 0.1, 10.0, -20.0, 150.0 } },
			}},
			["guitar2"] = { Dict = "switch@trevor@guitar_beatdown", Name = "001370_02_trvs_8_guitar_beatdown_idle_busker", Flag = 49, Props = {
				{ Model = "prop_acc_guitar_01", Bone = 24818, Offset = { -0.05, 0.31, 0.1, 10.0, -20.0, 150.0 } },
			}},
			["guitarelectric"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
				{ Model = "prop_el_guitar_01", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
			}},
			["guitarelectric2"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
				{ Model = "prop_el_guitar_02", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
			}},
			["guitarelectric3"] = { Dict = "amb@world_human_musician@guitar@male@idle_a", Name = "idle_b", Flag = 49, Props = {
				{ Model = "prop_el_guitar_03", Bone = 24818, Offset = { -0.07, 0.31, 0.15, 20.0, -18.0, 150.0 } },
			}},
			["book"] = { Dict = "cellphone@", Name = "cellphone_text_read_base", Flag = 49, Props = {
				{ Model = "prop_novel_01", Bone = 6286, Offset = { 0.15, 0.03, -0.055, 0.0, 180.0, -90.0 } },
			}},
			["bouquet"] = { Dict = "impexp_int-0", Name = "mp_m_waremech_01_dual-0", Flag = 49, Props = {
				{ Model = "prop_snow_flower_02", Bone = 24817, Offset = { -0.29, 0.40, -0.02, -90.0, -90.0, 0.0 } },
			}},
			["teddy"] = { Dict = "impexp_int-0", Name = "mp_m_waremech_01_dual-0", Flag = 49, Props = {
				{ Model = "v_ilev_mr_rasberryclean", Bone = 24817, Offset = { -0.20, 0.46, -0.016, -180.0, -90.0, 0.0 } },
			}},
			["backpack"] = { Dict = "move_p_m_zero_rucksack", Name = "idle", Flag = 49, Props = {
				{ Model = "p_michael_backpack_s", Bone = 24818, Offset = { 0.07, -0.11, -0.05, 0.0, -90.0, 175.0 } },
			}},
			["clipboard"] = { Dict = "missfam4", Name = "base", Flag = 49, Props = {
				{ Model = "p_amb_clipboard_01", Bone = 36029, Offset = { 0.16, 0.08, 0.1, -130.0, -50.0, 0.0 } },
			}},
			["map"] = { Dict = "amb@world_human_tourist_map@male@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_tourist_map_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["begger"] = { Dict = "amb@world_human_bum_freeway@male@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_beggers_sign_03", Bone = 58868, Offset = { 0.19, 0.18, 0.0, 5.0, 0.0, 40.0 } },
			}},
			["makeitrain"] = { Dict = "anim@mp_player_intupperraining_cash", Name = "idle_a", Flag = 49, Props = {
				{ Model = "prop_anim_cash_pile_01", Bone = 60309, Offset = { 0.0, 0.0, 0.0, 180.0, 0.0, 70.0 } },
			}},
			["camera"] = { Dict = "amb@world_human_paparazzi@male@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_pap_camera_01", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}, Evidence = true },
			["champagnespray"] = { Dict = "anim@mp_player_intupperspray_champagne", Name = "idle_a", Flag = 49, Props = {
				{ Model = "ba_prop_battle_champ_open", Bone = 28422, Offset = { 0.0,0.0,0.0,0.0,0.0,0.0 } },
			}},
			["phonecall"] = { Dict = "cellphone@", Name = "cellphone_call_listen_base", Flag = 49, Props = {
				{ Model = "prop_npc_phone_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["phone"] = { Dict = "cellphone@", Name = "cellphone_text_read_base", Flag = 49, Props = {
				{ Model = "prop_npc_phone_02", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 } },
			}},
			["clean"] = { Dict = "timetable@floyd@clean_kitchen@base", Name = "base", Flag = 49, Props = {
				{ Model = "prop_sponge_01", Bone = 28422, Offset = { 0.0, 0.0, -0.01, 90.0, 0.0, 0.0 } },
			}},
			["clean2"] = { Dict = "amb@world_human_maid_clean@", Name = "base", Flag = 49, Props = {
				{ Model = "prop_sponge_01", Bone = 28422, Offset = { 0.0, 0.0, -0.01, 90.0, 0.0, 0.0 } },
			}},
			["pizza"] = { Dict = "amb@code_human_wander_eating_donut_fat@female@base", Name = "static", Flag = 49, Props = {
				{ Model = "v_res_tt_pizzaplate", Bone = 28422, Offset = { 0.0, 0.0, 0.0, 90.0, 0.0, 0.0 } },
			}},
		},
	},
	{
		Name = "Other",
		Icon = "more",
		Emotes = {
			["actor"] = { Dict = "special_ped@mani@monologue_7@monologue_7b", Name = "soyunactor_1", Flag = 48 },
			["actor2"] = { Dict = "special_ped@mani@monologue_7@monologue_7e", Name = "soyunactor_4", Flag = 48 },
			["actress"] = { Dict = "missmic4premiere", Name = "prem_actress_star_a", Flag = 0 },
			["agitated"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_a", Flag = 0 },
			["agitated2"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_b", Flag = 0 },
			["agitated3"] = { Dict = "random@car_thief@agitated@idle_a", Name = "agitated_idle_c", Flag = 1 },
			["airhump"] = { Dict = "anim@mp_player_intcelebrationmale@air_shagging", Name = "air_shagging", Flag = 8 },
			["angry"] = { Dict = "switch@trevor@bridge", Name = "agressive_a", Flag = 48 },
			["angry2"] = { Dict = "switch@trevor@bridge", Name = "agressive_b", Flag = 48 },
			["argue"] = { Dict = "oddjobs@assassinate@vice@hooker", Name = "argue_a", Flag = 48 },
			["argue2"] = { Dict = "oddjobs@assassinate@vice@hooker", Name = "argue_b", Flag = 48 },
			["assure"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "average_car", Flag = 48 },
			["beg"] = { Dict = "oddjobs@bailbond_mountain", Name = "excited_idle_c", Flag = 48 },
			["beg2"] = { Dict = "oddjobs@bailbond_mountain", Name = "excited_idle_b", Flag = 48 },
			["berate"] = { Dict = "misscarsteal4@actor", Name = "actor_berating_assistant", Flag = 48 },
			["bigshot"] = { Dict = "special_ped@mani@monologue_8@monologue_8c", Name = "miranmemiranme_2", Flag = 48 },
			["bigshot2"] = { Dict = "special_ped@mani@monologue_8@monologue_8b", Name = "miranmemiranme_1", Flag = 48 },
			["bird"] = { Dict = "random@peyote@bird", Name = "wakeup", Flag = 48 },
			["blowkisses"] = { Dict = "anim@mp_player_intcelebrationfemale@blow_kiss", Name = "blow_kiss", Flag = 8 },
			["boi"] = { Dict = "special_ped@jane@monologue_5@monologue_5c", Name = "brotheradrianhasshown_2", Flag = 48 },
			["bouncer"] = { Dict = "mini@strip_club@idles@bouncer@idle_c", Name = "idle_c", Flag = 49 },
			["bow"] = { Dict = "anim@arena@celeb@podium@no_prop@", Name = "regal_c_1st", Flag = 48, BlendSpeed = 1.0 },
			["bow2"] = { Dict = "anim@arena@celeb@podium@no_prop@", Name = "regal_a_1st", Flag = 48, BlendSpeed = 1.0 },
			["boxing"] = { Dict = "anim@mp_player_intcelebrationmale@shadow_boxing", Name = "shadow_boxing", Flag = 0 },
			["boxing2"] = { Dict = "anim@mp_player_intcelebrationfemale@shadow_boxing", Name = "shadow_boxing", Flag = 0 },
			["bringit2"] = { Dict = "mini@triathlon", Name = "want_some_of_this", Flag = 48 },
			["bringit3"] = { Dict = "mini@triathlon", Name = "wot_the_fuck", Flag = 48 },
			["bringiton"] = { Dict = "misscommon@response", Name = "bring_it_on", Flag = 48 },
			["brolove"] = { Dict = "mp_player_int_upperbro_love", Name = "mp_player_int_bro_love_enter", Flag = 48 },
			["browse"] = { Dict = "amb@world_human_window_shop@male@idle_a", Name = "browse_a", Flag = 48 },
			["buttpick"] = { Dict = "friends@frt@ig_1", Name = "trevor_impatient_wait_3", Flag = 48 },
			["callover"] = { Dict = "anim@heists@prison_heistig_2_p1_exit_bus", Name = "react_a_guard_a", Flag = 48 },
			["cc"] = { Dict = "amb@code_human_police_crowd_control@idle_a", Name = "idle_a", Flag = 1 },
			["cc2"] = { Dict = "amb@code_human_police_crowd_control@idle_a", Name = "idle_b", Flag = 1 },
			["cc3"] = { Dict = "amb@code_human_police_crowd_control@idle_b", Name = "idle_d", Flag = 1 },
			["celebrate"] = { Dict = "rcmfanatic1celebrate", Name = "celebrate", Flag = 48 },
			["charm"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "charm", Flag = 48 },
			["checkout"] = { Dict = "clothingspecs", Name = "try_glasses_neutral_a", Flag = 48 },
			["checkout2"] = { Dict = "clothingtrousers", Name = "check_out_a", Flag = 0 },
			["checkout3"] = { Dict = "clothingtrousers", Name = "check_out_c", Flag = 0 },
			["cheer"] = { Dict = "amb@world_human_cheering@female_c", Name = "base", Flag = 1 },
			["cheer2"] = { Dict = "amb@world_human_cheering@male_b", Name = "base", Flag = 1 },
			["cheer3"] = { Dict = "mini@triathlon", Name = "male_unarmed_a", Flag = 1 },
			["cheer4"] = { Dict = "mini@triathlon", Name = "male_unarmed_b", Flag = 1 },
			["cheer5"] = { Dict = "random@street_race", Name = "_streetracer_accepted", Flag = 0 },
			["cheer6"] = { Dict = "amb@world_human_cheering@female_d", Name = "base", Flag = 49 },
			["cheer7"] = { Dict = "amb@world_human_cheering@male_a", Name = "base", Flag = 49 },
			["clap"] = { Dict = "amb@world_human_cheering@male_a", Name = "base", Flag = 48 },
			["clapangry"] = { Dict = "anim@arena@celeb@flat@solo@no_props@", Name = "angry_clap_a_player_a", Flag = 0 },
			["clapslow"] = { Dict = "anim@mp_player_intcelebrationmale@slow_clap", Name = "slow_clap", Flag = 48 },
			["clapslow2"] = { Dict = "anim@mp_player_intcelebrationfemale@slow_clap", Name = "slow_clap", Flag = 48 },
			["clapslow3"] = { Dict = "anim@mp_player_intupperslow_clap", Name = "idle_a", Flag = 49 },
			["cmon2"] = { Dict = "fra_0_int-16", Name = "ig_lamardavis-16", Flag = 48, Duration = 3000 },
			["confused"] = { Dict = "anim@amb@code_human_patrol@male@1h@idle_a", Name = "idle_a", Flag = 48 },
			["cop"] = { Dict = "amb@world_human_cop_idles@male@idle_a", Name = "idle_c", Flag = 49 },
			["count"] = { Dict = "special_ped@jane@monologue_5@monologue_5d", Name = "brotheradrianhasshown_3", Flag = 48 },
			["cower"] = { Dict = "amb@code_human_cower@male@idle_b", Name = "idle_d", Flag = 1 },
			["cower2"] = { Dict = "amb@code_human_cower@female@idle_a", Name = "idle_c", Flag = 1 },
			["cower3"] = { Dict = "amb@code_human_cower_stand@male@idle_a", Name = "idle_b", Flag = 49 },
			["cpr"] = { Dict = "missheistfbi3b_ig8_2", Name = "cpr_loop_paramedic", Flag = 1 },
			["crawl"] = { Dict = "move_injured_ground", Name = "front_loop", Flag = 1 },
			["crossarms"] = { Dict = "missheistdockssetup1showoffcar@base", Name = "base_5", Flag = 49 },
			["crossarms2"] = { Dict = "random@street_race", Name = "_car_b_lookout", Flag = 49 },
			["crossarms3"] = { Dict = "mp_corona@single_team", Name = "single_team_loop_boss", Flag = 49 },
			["crossarms4"] = { Dict = "anim@amb@nightclub@peds@", Name = "rcmme_amanda1_stand_loop_cop", Flag = 49 },
			["crossarms5"] = { Dict = "missfbi5ig_36", Name = "_idle", Flag = 49 },
			["crossarms6"] = { Dict = "random@shop_gunstore", Name = "_idle", Flag = 49 },
			["crossarms7"] = { Dict = "mini@hookers_spvanilla", Name = "idle_reject_loop_a", Flag = 49 },
			["crossroad"] = { Dict = "amb@code_human_cross_road@female@idle_a", Name = "idle_c", Flag = 1 },
			["crossroad2"] = { Dict = "amb@code_human_cross_road@male@idle_a", Name = "idle_e", Flag = 1 },
			["cutthroat"] = { Dict = "anim@mp_player_intcelebrationfemale@cut_throat", Name = "cut_throat", Flag = 1 },
			["dab"] = { Dict = "amb@world_human_statue@base", Name = "base", Flag = 48 },
			["dazed"] = { Dict = "misscarsteal4@actor", Name = "dazed_idle", Flag = 49 },
			["dealer"] = { Dict = "amb@world_human_drug_dealer_hard@male@idle_a", Name = "idle_a", Flag = 1 },
			["dealer2"] = { Dict = "amb@world_human_drug_dealer_hard@male@idle_b", Name = "idle_d", Flag = 1 },
			["depressed"] = { Dict = "amb@world_human_bum_standing@depressed@idle_a", Name = "idle_a", Flag = 49 },
			["depressed2"] = { Dict = "oddjobs@bailbond_hobodepressed", Name = "idle_a", Flag = 49 },
			["depressed3"] = { Dict = "oddjobs@bailbond_hobodepressed", Name = "idle_c", Flag = 49 },
			["distressed"] = { Dict = "random@domestic", Name = "f_distressed_loop", Flag = 1 },
			["dj"] = { Dict = "anim@mp_player_intcelebrationfemale@dj", Name = "dj", Flag = 49 },
			["dj2"] = { Dict = "anim@mp_player_intcelebrationmale@dj", Name = "dj", Flag = 49 },
			["drunk"] = { Dict = "amb@world_human_bum_standing@drunk@idle_a", Name = "idle_a", Flag = 1 },
			["dustoff"] = { Dict = "reaction@shake_it_off@", Name = "dustoff", Flag = 48 },
			["dustoff2"] = { Dict = "clothingshirt", Name = "try_shirt_positive_d", Flag = 48 },
			["dustoff3"] = { Dict = "mini@racing@quad@", Name = "offroad_outro_trv", Flag = 48 },
			["explain"] = { Dict = "special_ped@baygor@michael_1@michael_1f", Name = "hey_how_you_doing_5", Flag = 48 },
			["explain2"] = { Dict = "special_ped@baygor@michael_1@michael_1g", Name = "hey_how_you_doing_6", Flag = 48 },
			["explain3"] = { Dict = "special_ped@baygor@michael_1@michael_1h", Name = "hey_how_you_doing_7", Flag = 48 },
			["explain4"] = { Dict = "special_ped@baygor@michael_1@michael_1k", Name = "hey_how_you_doing_10", Flag = 48 },
			["explain5"] = { Dict = "special_ped@baygor@michael_2@michael_2b", Name = "hey_how_you_doing2_1", Flag = 48 },
			["explain6"] = { Dict = "special_ped@clinton@monologue_14@monologue_14b", Name = "you_know_what_they_1", Flag = 48 },
			["facepalm"] = { Dict = "anim@mp_player_intcelebrationfemale@face_palm", Name = "face_palm", Flag = 48 },
			["facepalm2"] = { Dict = "anim@mp_player_intcelebrationmale@face_palm", Name = "face_palm", Flag = 48 },
			["fail"] = { Dict = "anim@heists@ornate_bank@chat_manager", Name = "fail", Flag = 48 },
			["fallover"] = { Dict = "random@drunk_driver_1", Name = "drunk_fall_over", Flag = 2 },
			["fancy"] = { Dict = "random@shop_clothes@mid", Name = "_idle_a", Flag = 1 },
			["fancy2"] = { Dict = "random@shop_clothes@mid", Name = "_idle_b", Flag = 1 },
			["fingerkiss"] = { Dict = "anim@mp_player_intupperfinger_kiss", Name = "idle_a", Flag = 48 },
			["fixtie"] = { Dict = "clothingtie", Name = "try_tie_positive_d", Flag = 48 },
			["flinch"] = { Dict = "missarmenian2", Name = "fake_punch_walk_by_lamar", Flag = 48, Duration = 2500 },
			["flip"] = { Dict = "anim@arena@celeb@flat@solo@no_props@", Name = "flip_a_player_a", Flag = 0, Duration = 1950 },
			["flipoff"] = { Dict = "mp_player_int_upperfinger", Name = "mp_player_int_finger_01_enter", Flag = 0 },
			["flipoff2"] = { Dict = "mp_player_int_upperup_yours", Name = "mp_player_int_up_yours_enter", Flag = 0 },
			["followme"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_01", Flag = 48 },
			["followme2"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_02", Flag = 48 },
			["followme3"] = { Dict = "missarmenian1ig_13", Name = "lamar_idle_03", Flag = 48 },
			["forgetit"] = { Dict = "taxi_hail", Name = "forget_it", Flag = 48 },
			["freakout"] = { Dict = "anim@mp_player_intcelebrationmale@freakout", Name = "freakout", Flag = 8 },
			["freakout2"] = { Dict = "anim@mp_player_intcelebrationfemale@freakout", Name = "freakout", Flag = 8 },
			["frog"] = { Dict = "missexile3", Name = "ex03_train_roof_idle", Flag = 1 },
			["fu"] = { Dict = "mp_player_int_upperfinger", Name = "mp_player_int_finger_02_enter", Flag = 48 },
			["fu2"] = { Dict = "random@shop_robbery_reactions@", Name = "screw_you", Flag = 48 },
			["fyall"] = { Dict = "anim@mp_player_intcelebrationfemale@finger", Name = "finger", Flag = 48 },
			["fyall2"] = { Dict = "anim@mp_player_intupperfinger", Name = "idle_a", Flag = 48 },
			["gangidle"] = { Dict = "friends@frl@ig_1", Name = "idle_b_lamar", Flag = 1 },
			["gangidle2"] = { Dict = "misstrvram_4", Name = "thugs_idle_b", Flag = 1 },
			["gangsign"] = { Dict = "mp_player_int_uppergang_sign_a", Name = "mp_player_int_gang_sign_a", Flag = 49 },
			["gangsign2"] = { Dict = "mp_player_int_uppergang_sign_b", Name = "mp_player_int_gang_sign_b", Flag = 49 },
			["gangsign3"] = { Dict = "amb@code_human_in_car_mp_actions@gang_sign_a@std@ps@base", Name = "idle_a", Flag = 49 },
			["gangsign4"] = { Dict = "amb@code_human_in_car_mp_actions@gang_sign_b@std@ps@base", Name = "idle_a", Flag = 49 },
			["golfswing"] = { Dict = "rcmnigel1d", Name = "swing_a_mark", Flag = 0, Duration = 4000 },
			["airguitar"] = { Dict = "anim@mp_player_intcelebrationfemale@air_guitar", Name = "air_guitar", Flag = 0 },
			["give"] = { Dict = "mp_common", Name = "givetake1_a", Flag = 0 },
			["handsonhip"] = { Dict = "timetable@amanda@ig_2", Name = "ig_2_base_amanda", Flag = 49 },
			["handsonhip2"] = { Dict = "missfbi2@leadinoutfbi_2_mcs_1", Name = "_leadin_action_fbi", Flag = 49 },
			["handsonhip3"] = { Dict = "misshair_shop@hair_dressers", Name = "keeper_idle_a", Flag = 49 },
			["handsonhip4"] = { Dict = "random@shop_tattoo", Name = "_idle", Flag = 49 },
			["handsonhip5"] = { Dict = "missfbi5leadinout", Name = "leadin_2_fra", Flag = 49 },
			["handsup"] = { Dict = "missminuteman_1ig_2", Name = "handsup_base", Flag = 49, HandsUp = true, Disarm = true },
			["handsup2"] = { Dict = "missfra1mcs_2_crew_react", Name = "handsup_standing_base", Flag = 49, HandsUp = true, Disarm = true },
			["handsup3"] = { Dict = "missfra1mcs_2_crew_react", Name = "idle_m_camera", Flag = 49, HandsUp = true, Disarm = true },
			["handsup4"] = { Dict = "anim@move_hostages@female", Name = "female_idle", Flag = 49, HandsUp = true, Disarm = true },
			["handsup5"] = { Dict = "anim@move_hostages@male", Name = "male_idle", Flag = 49, HandsUp = true, Disarm = true },
			["handsup6"] = { Dict = "misscarsteal2chad_garage", Name = "chad_parking_garage_handsuploop_chad", Flag = 49, HandsUp = true, Disarm = true },
			["hangout"] = { Dict = "amb@world_human_hang_out_street@female_arm_side@idle_a", Name = "idle_a", Flag = 1 },
			["hangout2"] = { Dict = "amb@world_human_hang_out_street@female_arms_crossed@idle_a", Name = "idle_a", Flag = 49 },
			["hangout3"] = { Dict = "amb@world_human_hang_out_street@female_hold_arm@idle_a", Name = "idle_a", Flag = 49 },
			["hangout4"] = { Dict = "amb@world_human_hang_out_street@male_a@idle_a", Name = "idle_a", Flag = 48 },
			["hangout5"] = { Dict = "amb@world_human_hang_out_street@male_b@idle_a", Name = "idle_b", Flag = 1 },
			["hangout6"] = { Dict = "amb@world_human_hang_out_street@male_c@idle_a", Name = "idle_a", Flag = 48 },
			["hangout7"] = { Dict = "oddjobs@bailbond_surf_farm", Name = "base", Flag = 1 },
			["headbutt"] = { Dict = "melee@unarmed@streamed_variations", Name = "plyr_takedown_front_headbutt", Flag = 48 },
			["helpme"] = { Dict = "random@bicycle_thief@ask_help", Name = "please_man_you_gotta_help_me", Flag = 48 },
			["helpme2"] = { Dict = "random@bicycle_thief@ask_help", Name = "i_cant_catch_him_on_foot", Flag = 48 },
			["hitch"] = { Dict = "random@hitch_lift", Name = "idle_f", Flag = 49 },
			["hitch2"] = { Dict = "random@hitch_lift", Name = "carjack_mainloop_female", Flag = 0 },
			["holster"] = { Dict = "reaction@intimidation@cop@unarmed", Name = "intro", Flag = 50 },
			["hooker"] = { Dict = "amb@world_human_prostitute@cokehead@idle_a", Name = "idle_b", Flag = 1 },
			["hooker2"] = { Dict = "amb@world_human_prostitute@crackhooker@idle_a", Name = "idle_c", Flag = 9 },
			["huh"] = { Dict = "clothingtie", Name = "check_out_a", Flag = 48 },
			["hurry"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_b", Flag = 0 },
			["hurry2"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_e", Flag = 0 },
			["hurry3"] = { Dict = "missheist_agency3aig_18", Name = "say_hurry_up_f", Flag = 0 },
			["impatient"] = { Dict = "amb@world_human_stand_impatient@female@no_sign@idle_a", Name = "idle_c", Flag = 1 },
			["impatient2"] = { Dict = "amb@world_human_stand_impatient@female@no_sign@idle_a", Name = "idle_a", Flag = 49 },
			["impatient3"] = { Dict = "amb@world_human_stand_impatient@male@no_sign@idle_a", Name = "idle_a", Flag = 49 },
			["impatient4"] = { Dict = "friends@fra@ig_1", Name = "impatient_idle_a", Flag = 9 },
			["impatient5"] = { Dict = "friends@fra@ig_1", Name = "base_idle", Flag = 9 },
			["impatient6"] = { Dict = "friends@frf@ig_1", Name = "impatient_idle_c", Flag = 9 },
			["impatient7"] = { Dict = "friends@frt@ig_1", Name = "trevor_impatient_wait_1", Flag = 9 },
			["investigate"] = { Dict = "amb@world_human_guard_patrol@male@idle_b", Name = "idle_e", Flag = 0, Evidence = true },
			["investigate2"] = { Dict = "amb@world_human_guard_patrol@male@idle_a", Name = "idle_a", Flag = 0, Evidence = true },
			["investigate3"] = { Dict = "amb@code_human_police_investigate@idle_a", Name = "idle_a", Flag = 0, Evidence = true },
			["jazzhands"] = { Dict = "anim@mp_player_intcelebrationfemale@jazz_hands", Name = "jazz_hands", Flag = 48 },
			["jazzhands2"] = { Dict = "anim@mp_player_intcelebrationmale@jazz_hands", Name = "jazz_hands", Flag = 48 },
			["karate"] = { Dict = "anim@mp_player_intcelebrationfemale@karate_chops", Name = "karate_chops", Flag = 0 },
			["karate2"] = { Dict = "anim@mp_player_intcelebrationmale@karate_chops", Name = "karate_chops", Flag = 0 },
			["kc"] = { Dict = "anim@mp_player_intcelebrationfemale@knuckle_crunch", Name = "knuckle_crunch", Flag = 48 },
			["kickrocks"] = { Dict = "anim@mp_freemode_return@f@fail", Name = "fail_a", Flag = 0 },
			["knees"] = { Dict = "missprologueig_1", Name = "idle_loop_malehostage01", Flag = 1 },
			["knees2"] = { Dict = "missprologueig_2", Name = "idle_on_floor_malehostage02", Flag = 1 },
			["knockdoor"] = { Dict = "missheistfbi3b_ig7", Name = "lift_fibagent_loop", Flag = 48 },
			["lay"] = { Dict = "switch@trevor@annoys_sunbathers", Name = "trev_annoys_sunbathers_loop_girl", Flag = 1 },
			["lay2"] = { Dict = "switch@trevor@annoys_sunbathers", Name = "trev_annoys_sunbathers_loop_guy", Flag = 1 },
			["leanchill"] = { Dict = "amb@world_human_leaning@male@wall@back@hands_together@idle_b", Name = "idle_e", Flag = 1 },
			["leanchill2"] = { Dict = "amb@world_human_leaning@male@wall@back@legs_crossed@idle_a", Name = "idle_c", Flag = 1 },
			["leanflirt"] = { Dict = "random@street_race", Name = "_car_a_flirt_girl", Flag = 48 },
			["leanrail"] = { Dict = "missstrip_club_lean", Name = "player_lean_rail_loop", Flag = 1 },
			["leanrail2"] = { Dict = "amb@prop_human_seat_bar@male@hands_on_bar@idle_b", Name = "idle_d", Flag = 49 },
			["ledge"] = { Dict = "missfbi1", Name = "ledge_loop", Flag = 1 },
			["listen"] = { Dict = "special_ped@andy_moon@monologue_11@monologue_11e", Name = "andy_ig_1_p11_dontworrywhentheyroastyou_4", Flag = 48 },
			["lol"] = { Dict = "anim@arena@celeb@flat@paired@no_props", Name = "laugh_a_player_b", Flag = 48 },
			["lookforchange"] = { Dict = "amb@prop_human_parking_meter@male@base", Name = "base", Flag = 49 },
			["makeitrain"] = { Dict = "anim@mp_player_intupperraining_cash", Name = "idle_a_fp", Flag = 48 },
			["mechfix"] = { Dict = "mini@repair", Name = "fixing_a_player", Flag = 1 },
			["mechfix2"] = { Dict = "anim@amb@clubhouse@tutorial@bkr_tut_ig3@", Name = "machinic_loop_mechandplayer", Flag = 1 },
			["mechfix3"] = { Dict = "missmechanic", Name = "work2_base", Flag = 1 },
			["mechfix4"] = { Dict = "missmechanic", Name = "work_base", Flag = 1 },
			["mechfix5"] = { Dict = "anim@amb@garage@chassis_repair@", Name = "idle_01_amy_skater_01", Flag = 1 },
			["medic"] = {
				Sequence = {
					{ Dict = "amb@medic@standing@kneel@enter", Name = "enter", Flag = 0 },
					{ Dict = "amb@medic@standing@kneel@idle_a", Name = "idle_a", Flag = 1 },
					{ Dict = "amb@medic@standing@kneel@exit", Name = "exit", Flag = 0, Locked = true },
				},
			},
			["meditate"] = { Dict = "rcmcollect_paperleadinout@", Name = "meditiate_idle", Flag = 1 },
			["meditate2"] = { Dict = "misscarsteal1leadin", Name = "devon_idle_02", Flag = 1 },
			["meditate3"] = { Dict = "mp_fm_intro_cut", Name = "base_loop", Flag = 1 },
			["middlefinger"] = { Dict = "anim@mp_player_intselfiethe_bird", Name = "idle_a", Flag = 49 },
			["mime"] = { Dict = "special_ped@mime", Name = "idle_c", Flag = 0 },
			["mindblown"] = { Dict = "anim@mp_player_intcelebrationmale@mind_blown", Name = "mind_blown", Flag = 48 },
			["mindblown2"] = { Dict = "anim@mp_player_intcelebrationfemale@mind_blown", Name = "mind_blown", Flag = 0 },
			["nails"] = { Dict = "missfbi3_camcrew", Name = "final_loop_gal", Flag = 49 },
			["negative"] = { Dict = "clothingshirt", Name = "try_shirt_negative_b", Flag = 48 },
			["nervous"] = { Dict = "mp_missheist_countrybank@nervous", Name = "nervous_idle", Flag = 1 },
			["never"] = { Dict = "special_ped@andy_moon@monologue_10@monologue_10d", Name = "andy_ig_1_p10_madethemangrypraytoyour401k_3", Flag = 48 },
			["no4"] = { Dict = "mini@triathlon", Name = "u_cant_do_that", Flag = 48 },
			["nope"] = { Dict = "anim@mp_player_intupperno_way", Name = "idle_a", Flag = 48 },
			["overhere"] = { Dict = "friends@frf@ig_1", Name = "over_here_idle_a", Flag = 48 },
			["overhere2"] = { Dict = "friends@frf@ig_1", Name = "over_here_idle_b", Flag = 48 },
			["overhere3"] = { Dict = "friends@frl@ig_1", Name = "waive_c_lamar", Flag = 48 },
			["passout"] = { Dict = "missarmenian2", Name = "drunk_loop", Flag = 1 },
			["passout2"] = { Dict = "random@mugging4", Name = "flee_backward_loop_shopkeeper", Flag = 1 },
			["peace"] = { Dict = "mp_player_int_upperpeace_sign", Name = "mp_player_int_peace_sign", Flag = 49 },
			["peace2"] = { Dict = "anim@mp_player_intupperpeace", Name = "idle_a", Flag = 49 },
			["peek"] = { Dict = "random@paparazzi@peek", Name = "left_peek_a", Flag = 1 },
			["peek2"] = { Dict = "anim@amb@machinery@vertical_mill@", Name = "look_high_amy_skater_01", Flag = 1 },
			["pickup"] = { Dict = "anim@am_hold_up@male", Name = "shoplift_low", Flag = 48 },
			["pickup2"] = { Dict = "random@domestic", Name = "pickup_low", Flag = 48 },
			["piss"] = { Dict = "missbigscore1switch_trevor_piss", Name = "piss_loop", Flag = 1 },
			["positive"] = { Dict = "clothingshirt", Name = "try_shirt_positive_a", Flag = 48 },
			["positive2"] = { Dict = "clothingshirt", Name = "try_shirt_positive_b", Flag = 48 },
			["praise"] = { Dict = "rcmepsilonism8", Name = "worship_base", Flag = 49 },
			["praise2"] = { Dict = "rcmepsilonism8", Name = "worship_idle_a", Flag = 49 },
			["pullover"] = { Dict = "misscarsteal3pullover", Name = "pull_over_right", Flag = 48 },
			["rabbit"] = { Dict = "random@peyote@rabbit", Name = "wakeup", Flag = 0 },
			["rain"] = { Dict = "amb@code_human_wander_rain@male_b@idle_a", Name = "idle_a", Flag = 49 },
			["rain2"] = { Dict = "amb@code_human_wander_rain@male_b@idle_a", Name = "idle_c", Flag = 49 },
			["raiseroof"] = { Dict = "anim@mp_player_intupperraise_the_roof", Name = "idle_a", Flag = 49 },
			["rockout"] = { Dict = "mp_player_int_upperrock", Name = "mp_player_int_rock_enter", Flag = 0 },
			["rockout2"] = { Dict = "anim@mp_player_intcelebrationmale@rock", Name = "rock", Flag = 0 },
			["rubhands"] = { Dict = "timetable@jimmy@ig_5@base", Name = "base", Flag = 48 },
			["salute"] = { Dict = "mp_player_int_uppersalute", Name = "mp_player_int_salute", Flag = 1 },
			["salute2"] = { Dict = "anim@mp_player_intcelebrationmale@salute", Name = "salute", Flag = 48 },
			["search"] = { Dict = "clothingshoes", Name = "check_out_a", Flag = 1, Evidence = true },
			["search2"] = { Dict = "clothingshoes", Name = "try_shoes_positive_a", Flag = 1, Evidence = true },
			["shh"] = { Dict = "anim@mp_player_intuppershush", Name = "idle_a_fp", Flag = 49 },
			["shit"] = { Dict = "missfbi3ig_0", Name = "shit_loop_trev", Flag = 1 },
			["shower"] = { Dict = "mp_safehouseshower@female@", Name = "shower_idle_a", Flag = 1 },
			["shower2"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_a", Flag = 1 },
			["shower3"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_b", Flag = 1 },
			["shower4"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_c", Flag = 1 },
			["shower5"] = { Dict = "mp_safehouseshower@male@", Name = "male_shower_idle_d", Flag = 1 },
			["sleepwalk"] = { Dict = "mp_sleep", Name = "sleep_loop", Flag = 49 },
			["slowclap2"] = { Dict = "anim@mp_player_intcelebrationfemale@slow_clap", Name = "slow_clap", Flag = 48 },
			["slowclap3"] = { Dict = "anim@mp_player_intcelebrationmale@slow_clap", Name = "slow_clap", Flag = 48 },
			["slumped2"] = { Dict = "amb@world_human_bum_slumped@male@laying_on_right_side@idle_a", Name = "idle_a", Flag = 1 },
			["smell"] = { Dict = "move_p_m_two_idles@generic", Name = "fidget_sniff_fingers", Flag = 49, Duration = 4000 },
			["spiderman"] = { Dict = "missexile3", Name = "ex03_train_roof_idle", Flag = 49 },
			["standingjog"] = { Dict = "amb@world_human_jog_standing@female@idle_a", Name = "idle_a", Flag = 1 },
			["standingjog2"] = { Dict = "amb@world_human_jog_standing@male@fitidle_a", Name = "idle_a", Flag = 1 },
			["steeple"] = { Dict = "ep_8_rcm-2", Name = "cs_chrisformage_dual-2", Flag = 48, BlendIn = 1.0, BlendOut = 1.0 },
			["stink"] = { Dict = "anim@mp_player_intcelebrationfemale@stinker", Name = "stinker", Flag = 48 },
			["stink2"] = { Dict = "anim@mp_player_intupperstinker", Name = "idle_a", Flag = 48 },
			["stretch"] = { Dict = "switch@franklin@press_ups", Name = "stretch_long", Flag = 48 },
			["stretch2"] = { Dict = "switch@franklin@press_ups", Name = "stretch_short", Flag = 48 },
			["stretch3"] = { Dict = "switch@franklin@bed", Name = "stretch_short", Flag = 48 },
			["suicide"] = { Dict = "mp_suicide", Name = "pistol", Flag = 0 },
			["sunbathe3"] = { Dict = "amb@world_human_sunbathe@female@front@idle_a", Name = "idle_c", Flag = 1 },
			["sunbathe4"] = { Dict = "amb@world_human_sunbathe@male@front@idle_a", Name = "idle_a", Flag = 1 },
			["superhero"] = { Dict = "rcmbarry", Name = "base", Flag = 1 },
			["swatback"] = { Dict = "swat", Name = "you_back", Flag = 48 },
			["swatcome"] = { Dict = "swat", Name = "come", Flag = 48 },
			["swatforward"] = { Dict = "swat", Name = "you_fwd", Flag = 48 },
			["swatfreeze"] = { Dict = "swat", Name = "freeze", Flag = 48 },
			["swatgo"] = { Dict = "swat", Name = "go_fwd", Flag = 48 },
			["swatleft"] = { Dict = "swat", Name = "you_left", Flag = 48 },
			["swatokay"] = { Dict = "swat", Name = "understood", Flag = 48 },
			["swatrally"] = { Dict = "swat", Name = "rally_point", Flag = 48 },
			["swatright"] = { Dict = "swat", Name = "you_right", Flag = 48 },
			["t"] = { Dict = "nm@hands", Name = "hands_up", Flag = 49 },
			["taunt"] = { Dict = "switch@franklin@gang_taunt_p1", Name = "gang_taunt_loop_lamar", Flag = 48 },
			["taunt2"] = { Dict = "switch@franklin@gang_taunt_p1", Name = "gang_taunt_loop_thug_02", Flag = 48 },
			["taunt3"] = { Dict = "switch@franklin@gang_taunt_p3", Name = "gang_taunt_with_lamar_loop_lamar", Flag = 48 },
			["taunt4"] = { Dict = "switch@franklin@gang_taunt_p5", Name = "fras_ig_6_p5_loop_lamar", Flag = 48 },
			["taxi"] = { Dict = "taxi_hail", Name = "hail_taxi", Flag = 48 },
			["thanks"] = { Dict = "random@thanks", Name = "thanks_ps", Flag = 48 },
			["thanks2"] = { Dict = "random@arrests", Name = "thanks_male_05", Flag = 48 },
			["thehand"] = { Dict = "mini@prostitutestalk", Name = "street_argue_f_a", Flag = 8 },
			["think"] = { Dict = "mp_cp_stolen_tut", Name = "b_think", Flag = 48 },
			["thinking"] = { Dict = "misscarsteal4@aliens", Name = "rehearsal_base_idle_director", Flag = 49 },
			["thinking2"] = { Dict = "mini@hookers_spcokehead", Name = "idle_wait", Flag = 49 },
			["thinking3"] = { Dict = "anim_casino_a@amb@casino@games@spectate@cardtable@ped_male@stand@01a@base", Name = "base", Flag = 49 },
			["thinking4"] = { Dict = "anim@amb@casino@hangout@ped_male@stand@02b@idles", Name = "idle_a", Flag = 49 },
			["thumbsup"] = { Dict = "anim@mp_player_intselfiethumbs_up", Name = "idle_a", Flag = 49 },
			["thumbsup2"] = { Dict = "anim@mp_player_intincarthumbs_upstd@rps@", Name = "idle_a", Flag = 49 },
			["thumbsup3"] = { Dict = "anim@mp_player_intupperthumbs_up", Name = "idle_a", Flag = 49 },
			["thumbsup4"] = { Dict = "anim@mp_player_intincarthumbs_upstd@ds@", Name = "idle_a", Flag = 49 },
			["thumbsup5"] = { Dict = "anim@mp_player_intupperthumbs_up", Name = "idle_a_fp", Flag = 49 },
			["thumbsup6"] = { Dict = "anim@mp_player_intincarthumbs_upstd@ps@", Name = "idle_a", Flag = 49 },
			["thumbsup7"] = { Dict = "anim@mp_player_intincarthumbs_upstd@rds@", Name = "idle_a", Flag = 49 },
			["thumbsup8"] = { Dict = "random@shop_clothes@low", Name = "_reaction_a", Flag = 48 },
			["thumbsup9"] = { Dict = "anim@mp_player_intcelebrationfemale@thumbs_up", Name = "thumbs_up", Flag = 48 },
			["time"] = { Dict = "friends@frm@ig_1", Name = "greeting_idle_b", Flag = 48 },
			["timid"] = { Dict = "missfam6ig_7_tattoo", Name = "ig_7_idle_02_tracey", Flag = 1 },
			["tough"] = { Dict = "missbigscore1", Name = "idle_d", Flag = 1 },
			["tough2"] = { Dict = "missbigscore1", Name = "idle_e", Flag = 1 },
			["tough3"] = { Dict = "random@shop_gunstore", Name = "_idle_a", Flag = 1 },
			["tough4"] = { Dict = "random@shop_gunstore", Name = "_idle_b", Flag = 1 },
			["tourguide"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_a", Flag = 0 },
			["tourguide2"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_b", Flag = 0 },
			["tourguide3"] = { Dict = "random@bus_tour_guide@idle_a", Name = "idle_c", Flag = 8 },
			["traffic"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_a", Flag = 49 },
			["traffic2"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_c", Flag = 49 },
			["traffic3"] = { Dict = "missheist_agency2aig_1", Name = "direct_traffic_e", Flag = 49 },
			["twitchy"] = { Dict = "amb@world_human_bum_standing@twitchy@idle_a", Name = "idle_a", Flag = 49 },
			["twitchy2"] = { Dict = "oddjobs@bailbond_hobotwitchy", Name = "idle_b", Flag = 49 },
			["typing"] = { Dict = "mp_fib_grab", Name = "loop", Flag = 49 },
			["vsign"] = { Dict = "mp_player_int_upperv_sign", Name = "mp_player_int_v_sign", Flag = 0 },
			["wank"] = { Dict = "mp_player_int_upperwank", Name = "mp_player_int_wank_01", Flag = 0 },
			["wary"] = { Dict = "mp_am_hold_up", Name = "wary_loop", Flag = 1 },
			["what3"] = { Dict = "special_ped@baygor@monologue_1@monologue_1e", Name = "ask_you_a_question_4", Flag = 48 },
			["whatup"] = { Dict = "mp_intro_seq@ig_4_car_select@", Name = "idle_c_lamar", Flag = 48 },
			["whatup2"] = { Dict = "friends@frl@ig_1", Name = "waive_a_lamar", Flag = 48 },
			["whatup3"] = { Dict = "mp_intro_seq@ig_4_car_select@", Name = "idle_d_lamar", Flag = 48 },
			["whocares"] = { Dict = "anim@mp_celebration@draw@female", Name = "draw_react_female_b", Flag = 0 },
			["whocares2"] = { Dict = "anim@mp_celebration@draw@male", Name = "draw_react_male_b", Flag = 0 },
			["why"] = { Dict = "random@shop_robbery_reactions@", Name = "but_why", Flag = 48 },
			["why3"] = { Dict = "random@shop_robbery_reactions@", Name = "shock", Flag = 48 },
			["writhe"] = { Dict = "combat@damage@rb_writhe", Name = "rb_writhe_loop", Flag = 1 },
			["writhe2"] = { Dict = "combat@damage@writheidle_a", Name = "writhe_idle_a", Flag = 1 },
			["writhe3"] = { Dict = "random@dealgonewrong", Name = "idle_a", Flag = 1 },
			["writhe4"] = { Dict = "random@dealgonewrong", Name = "idle_b", Flag = 1 },
			["wtf"] = { Dict = "misscommon@response", Name = "numbnuts", Flag = 48 },
		},
	},
	{
		Name = "Shared",
		Icon = "music_note",
		Emotes = {
			["highfive"] = {
				Text = "👋 High Five",
				Start = { Dict = "mp_ped_interaction", Name = "highfive_guy_a", Flag = 2, Duration = 1000 },
				Source = { Dict = "mp_ped_interaction", Name = "highfive_guy_a", Flag = 0 },
				Target = { Dict = "mp_ped_interaction", Name = "highfive_guy_b", Flag = 0, Heading = 180.0, Offset = vector3(0.0, 1.15, 0.0) },
			},
			["handshake"] = {
				Text = "🤝 Handshake",
				Source = { Dict = "mp_ped_interaction", Name = "handshake_guy_a", Flag = 0 },
				Target = { Dict = "mp_ped_interaction", Name = "handshake_guy_b", Flag = 0, Heading = 180.0, Offset = vector3(0.0, 1.15, 0.0) },
			},
			["brohug"] = {
				Text = "✊ Bro Hug",
				Source = { Dict = "mp_ped_interaction", Name = "hugs_guy_a", Flag = 0 },
				Target = { Dict = "mp_ped_interaction", Name = "hugs_guy_b", Flag = 0, Heading = 180.0, Offset = vector3(0.0, 1.15, 0.0) },
			},
			["hug"] = {
				Text = "🤗 Hugs",
				Source = { Dict = "mp_ped_interaction", Name = "kisses_guy_a", Flag = 0 },
				Target = { Dict = "mp_ped_interaction", Name = "kisses_guy_b", Flag = 0, Heading = 180.0, Offset = vector3(0.0, 1.15, 0.0) },
			},
		},
	},
}